[
  {
  "id": 101,
  "first": "Meseret",
  "last": "Nasseer",
  "department": "Project Development"
  },
  {
  "id": 102,
  "first": "Memuna",
  "last": "Endale",
  "department": "Project Management"
  },
  {
  "id": 103,
  "first": "Abiti",
  "last": "Admassu",
  "department": "Project Management"
  },
  {
  "id": "104",
  "first": "Millien",
  "last": "John",
  "department": "Quality Assurance"
  },
   {
  "id": "105",
  "first": "Adraro",
  "last": "Biniam",
  "department": "Quality Assurance"
  }
]

